[package]
name = "udp_stream"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "3.0.0"
serialize_deserialize_u8_i32 = "0.1.34"
serde = { version = "1.0.104", features = ["derive"] }
bincode = "1.2.1"